# 1번 문제

In [77]:
import xml.etree.ElementTree as ET
tree = ET.parse('yahoo.xml')
root = tree.getroot()
result = []
for item in root.findall('channel/item'):
    title = item.find('title').text
    source = item.find('source').text
    url = item.find('source').attrib['url']
    result.append([title, source, url])
for item in result:
    print(item)

['These Are The 5 Best Stocks To Buy And Watch Now', "Investor's Business Daily", 'http://www.investors.com/']
['The IRS Is Cracking Down on These High-Income Earners. Are You One of Them?', 'SmartAsset', 'https://smartasset.com/']
['A Supreme Court dispute over a $15,000 IRS bill may be aimed at a never-enacted tax on billionaires', 'AP Finance', 'http://www.ap.org/']
['Seeking up to 11% Dividend Yield? Analysts Suggest 2 Dividend Stocks to Buy', 'TipRanks', 'https://www.tipranks.com/']
['The Big Mistakes People Make in Medicare—And How to Avoid Them', 'The Wall Street Journal', 'http://www.wsj.com/']
["Here's why gas prices are down, even in pricey California, as Israel-Hamas war escalates", 'USA TODAY', 'https://www.usatoday.com/money/']
['Rite Aid Files for Bankruptcy, Undone by Years of Losses', 'The Wall Street Journal', 'http://www.wsj.com/']
['Bank of America Is the Problem Child of Big Banks. Here’s How It Can Right the Ship.', 'Barrons.com', 'http://www.barrons.com/']
["Treasury bond auctions have been ugly lately, and weak demand could be a 'canary in the coal mine'", 'Business Insider', 'https://www.businessinsider.com/']
['South Korea to fine two Hong Kong banks for naked short-selling', 'Reuters', 'http://www.reuters.com/']
['Housing has never been this unaffordable - and home prices are only going to keep rising, Goldman Sachs says', 'Business Insider', 'https://www.businessinsider.com/']
['Giant Lithium Deal Collapses After Australian Billionaire Rinehart Steps In', 'Bloomberg', 'https://www.bloomberg.com/']
['Dow Jones Futures Rise As Market Rally Faces Key Test; Tesla Earnings Ahead', "Investor's Business Daily", 'http://www.investors.com/']
['Rite Aid Files for US Bankruptcy, Will Close More Stores', 'Bloomberg', 'https://www.bloomberg.com/']
['Drug retailer Rite Aid files for bankruptcy, gets $3.45 billion commitment', 'Reuters', 'http://www.reuters.com/']
["Charlie Munger is a fraction as wealthy as Warren Buffett. He'd be worth over $10 billion if he kept all of his Berkshire Hathaway stock.", 'Business Insider', 'https://www.businessinsider.com/']
['Stocks Are Poised to Rise Monday', 'Barrons.com', 'http://www.barrons.com/']
['IRS Rule Change Should Have You Rethinking How You Leave Assets to Heirs', 'SmartAsset', 'https://smartasset.com/']
['Nvidia, a $1 trillion AI powerhouse, is fine with remote work—and is ignoring the return-to-office trend', 'Fortune', 'http://fortune.com/']
['Automakers Have Big Hopes for EVs; Buyers Aren’t Cooperating', 'The Wall Street Journal', 'http://www.wsj.com/']
['Albemarle’s $4.16 Billion Lithium Bet Scuttled by Australia’s Richest Person', 'The Wall Street Journal', 'http://www.wsj.com/']
['Tesla, Netflix, and banks highlight earnings rush: The week ahead', 'Yahoo Finance', 'http://finance.yahoo.com/']
['An IPO Pro Buys More Palantir, Rivian, and Kenvue. It Sold Li Auto.', 'Barrons.com', 'http://www.barrons.com/']
['Time Is Running Out for the ‘Year of the Bond’ as Losses Mount', 'Bloomberg', 'https://www.bloomberg.com/']
["ExxonMobil's $60 billion Pioneer deal signals era of 'extreme consolidation' for oil industry", 'Yahoo Finance', 'http://finance.yahoo.com/']
['Novo Nordisk: Relentless Inflows Send Shares Soaring', 'FX Empire', 'https://www.fxempire.com/']
['Charles Schwab Earnings: What Its Third Quarter Report May Show', 'Barrons.com', 'http://www.barrons.com/']
['Living Paycheck to Paycheck Is Common, Even Among Those Who Make More Than $100,000', 'Barrons.com', 'http://www.barrons.com/']
['Microsoft closes the deal; Arm has Wall Street salivating: Weekly tech roundup', 'Investing.com', 'https://www.investing.com/']
['Major US pharmacy chain Rite Aid files for bankruptcy', 'AP Finance', 'http://www.ap.org/']
['Freight recession unlike any other in history', 'FreightWaves', 'https://www.freightwaves.com']
['Big Tech’s Profit Machine Is Propping Up S&P 500 Earnings', 'Bloomberg', 'https://www.bloomberg.com/']
['Vertex Pharmaceuticals: One Chart Explains the Mega Rally', 'FX Empire', 'https://www.fxempire.com/']
['Default risks loom for nearly $2 trillion of junk-rated debt as US companies hit with higher interest rates', 'Business Insider', 'https://www.businessinsider.com/']
['How Much Can I Make on Social Security?', 'Investopedia', 'http://www.investopedia.com/']
['Insurance Stocks Look Attractive Now. Metlife and 5 Other to Consider.', 'Barrons.com', 'http://www.barrons.com/']
['Eli Lilly: One Chart Explains why Shares are Surging', 'FX Empire', 'https://www.fxempire.com/']
['How Evergrande’s Chief Tried to Turn Things Around—and Failed', 'The Wall Street Journal', 'http://www.wsj.com/']
['Treasuries Fall Amid Efforts to Calm Middle East: Markets Wrap', 'Bloomberg', 'https://www.bloomberg.com/']
["Big banks are benefiting from higher rates. Their customers aren't.", 'Yahoo Finance', 'http://finance.yahoo.com/']
['The Right Time to Change From Mutual Funds to ETFS', 'Investopedia', 'http://www.investopedia.com/']
['China Tightens Rules on Short Selling in a Bid to Boost Stocks', 'Bloomberg', 'https://www.bloomberg.com/']
['Earnings Calendar Spotlight: Tesla Holds Up, But Sellers Knock Netflix Lower Ahead Of Q3 Results', "Investor's Business Daily", 'http://www.investors.com/']
['Here’s What’s In GM’s New Labor Deal With Unifor', 'Barrons.com', 'http://www.barrons.com/']
['Want a Discount? Pay in Cash.', 'The Wall Street Journal', 'http://www.wsj.com/']

# 2번 문제

In [78]:
import csv

with open('hospital.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    hospital = list(reader)
    print(hospital)
    
f.close()
with open('doctors.json', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    doctor = list(reader)
    print(doctor)

f.close()

[['Priscilla Arnold', 'Nephrologist', '326 Willow Street Rowlett, TX 75088', 'Trainee', '_Nephrology'], ['Jenna Floyd', 'Nephrologist', '68 Spring Street Marysville, OH 43040', 'Permanent', '_Nephrology'], ['Ollie Holloway', 'Nephrologist', '50 Water Street Gulfport, MS 39503', 'Visiting', '_Nephrology'], ['Dennis Young', 'Nephrologist', '986 Lexington Court Tacoma, WA 98444', 'Permanent', '_Nephrology'], ['Marlon Carpenter', 'Microbiologist', '146 Route 9 Media, PA 19063', 'Permanent', '_Microbiology'], ['Clayton Lynch', 'Microbiologist', '769 Sycamore Street Niles, MI 49120', 'Visiting', '_Microbiology'], ['Barbara Scott', 'Microbiologist', '621 Ridge Avenue Elkhart, IN 46514', 'Permanent', '_Microbiology'], ['Joe Powell', 'Oncologist', '230 Durham Road Allentown, PA 18102', 'Permanent', '_Oncology'], ['Anne Griffin', 'Oncologist', '755 Front Street South Vincentown, NJ 08088', 'Trainee', '_Oncology'], ['Frank Murphy', 'Oncologist', '15 College Avenue Great Falls, MT 59404', 'Permanent', '_Oncology'], ['Brandon Smith', 'Oncologist', '309 Aspen Drive West Roxbury, MA 02132', 'Permanent', '_Oncology'], ['Fred Hill', 'Cardiologist', '374 Westminster Drive Florence, SC 29501', 'Permanent', '_Cardiology'], ['Terry Thomas', 'Cardiologist', '418 Belmont Avenue Canyon Country, CA 91387', 'Trainee', '_Cardiology'], ['Louise Garcia', 'Cardiologist', '900 York Road Newark, NJ 07103', 'Visiting', '_Cardiology'], ['Gary Patterson', 'Cardiologist', '924 2nd Street New Castle, PA 16101', 'Permanent', '_Cardiology'], ['Samuel Gonzalez', 'Surgerist', '79 North Street Mishawaka, IN 46544', 'Permanent', '_General_Surgery'], ['Phillip Nelson', 'Surgerist', '973 Manor Drive Mcdonough, GA 30252', 'Permanent', '_General_Surgery'], ['Kathleen Perry', 'General Doctor', '830 Ashley Court Evansville, IN 47711', 'Permanent', '_Walk_in_Clinic'], ['Janice Williams', 'General Doctor', '577 13th Street Chesterfield, VA 23832', 'Permanent', '_Walk_in_Clinic'], ['Evelyn Cooper', 'General Doctor', '311 Route 44 Stamford, CT 06902', 'Trainee', '_Walk_in_Clinic'], ['Roy Johnson', 'General Doctor', '355 Cambridge Road Havertown, PA 19083', 'Permanent', '_Walk_in_Clinic']]
[['['], ['    {"Name": "Gary Patterson"', ' "Age": 50}', ''], ['    {"Name": "Samuel Gonzalez"', ' "Age": 47}', ''], ['    {"Name": "Brandon Smith"', ' "Age": 40}', ''], ['    {"Name": "Ollie Holloway"', ' "Age": 39}', ' '], ['    {"Name": "Janice Williams"', ' "Age": 47}', ''], ['    {"Name": "Evelyn Cooper"', ' "Age": 60}', ''], ['    {"Name": "Joe Powell"', ' "Age": 55}', ''], ['    {"Name": "Anne Griffin"', ' "Age": 45}', ''], ['    {"Name": "Priscilla Arnold"', ' "Age": 35}', ''], ['    {"Name": "Frank Murphy"', ' "Age": 39}', ''], ['    {"Name": "Dennis Young"', ' "Age": 35}', ''], ['    {"Name": "Fred Hill"', ' "Age": 41}', ''], ['    {"Name": "Terry Thomas"', ' "Age": 43}', ''], ['    {"Name": "Louise Garcia"', ' "Age": 38}', ''], ['    {"Name": "Marlon Carpenter"', ' "Age": 40}', ''], ['    {"Name": "Clayton Lynch"', ' "Age": 36}', ''], ['    {"Name": "Jenna Floyd"', ' "Age": 38}', ''], ['    {"Name": "Barbara Scott"', ' "Age": 52}', ''], ['    {"Name": "Phillip Nelson"', ' "Age": 45}', ''], ['    {"Name": "Kathleen Perry"', ' "Age": 45}', ' '], ['    {"Name": "Roy Johnson"', ' "Age": 59}'], [']']]

In [79]:
import json
with open('doctors.json', 'r', encoding='utf-8') as f:
    doctors = json.load(f)
    print(doctors)
    
f.close()

import csv
with open('hospital.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    hospital = list(reader)
    print(hospital)
    
f.close()

[{'Name': 'Gary Patterson', 'Age': 50}, {'Name': 'Samuel Gonzalez', 'Age': 47}, {'Name': 'Brandon Smith', 'Age': 40}, {'Name': 'Ollie Holloway', 'Age': 39}, {'Name': 'Janice Williams', 'Age': 47}, {'Name': 'Evelyn Cooper', 'Age': 60}, {'Name': 'Joe Powell', 'Age': 55}, {'Name': 'Anne Griffin', 'Age': 45}, {'Name': 'Priscilla Arnold', 'Age': 35}, {'Name': 'Frank Murphy', 'Age': 39}, {'Name': 'Dennis Young', 'Age': 35}, {'Name': 'Fred Hill', 'Age': 41}, {'Name': 'Terry Thomas', 'Age': 43}, {'Name': 'Louise Garcia', 'Age': 38}, {'Name': 'Marlon Carpenter', 'Age': 40}, {'Name': 'Clayton Lynch', 'Age': 36}, {'Name': 'Jenna Floyd', 'Age': 38}, {'Name': 'Barbara Scott', 'Age': 52}, {'Name': 'Phillip Nelson', 'Age': 45}, {'Name': 'Kathleen Perry', 'Age': 45}, {'Name': 'Roy Johnson', 'Age': 59}]
[['Priscilla Arnold', 'Nephrologist', '326 Willow Street Rowlett, TX 75088', 'Trainee', '_Nephrology'], ['Jenna Floyd', 'Nephrologist', '68 Spring Street Marysville, OH 43040', 'Permanent', '_Nephrology'], ['Ollie Holloway', 'Nephrologist', '50 Water Street Gulfport, MS 39503', 'Visiting', '_Nephrology'], ['Dennis Young', 'Nephrologist', '986 Lexington Court Tacoma, WA 98444', 'Permanent', '_Nephrology'], ['Marlon Carpenter', 'Microbiologist', '146 Route 9 Media, PA 19063', 'Permanent', '_Microbiology'], ['Clayton Lynch', 'Microbiologist', '769 Sycamore Street Niles, MI 49120', 'Visiting', '_Microbiology'], ['Barbara Scott', 'Microbiologist', '621 Ridge Avenue Elkhart, IN 46514', 'Permanent', '_Microbiology'], ['Joe Powell', 'Oncologist', '230 Durham Road Allentown, PA 18102', 'Permanent', '_Oncology'], ['Anne Griffin', 'Oncologist', '755 Front Street South Vincentown, NJ 08088', 'Trainee', '_Oncology'], ['Frank Murphy', 'Oncologist', '15 College Avenue Great Falls, MT 59404', 'Permanent', '_Oncology'], ['Brandon Smith', 'Oncologist', '309 Aspen Drive West Roxbury, MA 02132', 'Permanent', '_Oncology'], ['Fred Hill', 'Cardiologist', '374 Westminster Drive Florence, SC 29501', 'Permanent', '_Cardiology'], ['Terry Thomas', 'Cardiologist', '418 Belmont Avenue Canyon Country, CA 91387', 'Trainee', '_Cardiology'], ['Louise Garcia', 'Cardiologist', '900 York Road Newark, NJ 07103', 'Visiting', '_Cardiology'], ['Gary Patterson', 'Cardiologist', '924 2nd Street New Castle, PA 16101', 'Permanent', '_Cardiology'], ['Samuel Gonzalez', 'Surgerist', '79 North Street Mishawaka, IN 46544', 'Permanent', '_General_Surgery'], ['Phillip Nelson', 'Surgerist', '973 Manor Drive Mcdonough, GA 30252', 'Permanent', '_General_Surgery'], ['Kathleen Perry', 'General Doctor', '830 Ashley Court Evansville, IN 47711', 'Permanent', '_Walk_in_Clinic'], ['Janice Williams', 'General Doctor', '577 13th Street Chesterfield, VA 23832', 'Permanent', '_Walk_in_Clinic'], ['Evelyn Cooper', 'General Doctor', '311 Route 44 Stamford, CT 06902', 'Trainee', '_Walk_in_Clinic'], ['Roy Johnson', 'General Doctor', '355 Cambridge Road Havertown, PA 19083', 'Permanent', '_Walk_in_Clinic']]

In [80]:
doctor_list = []
for i in range(1, len(hospital)):
    for j in range(len(doctors)):
        if hospital[i][0] == doctors[j]['Name']:
            hospital[i].append(doctors[j]['Age'])
            doctor_list.append(hospital[i])
            break
print(doctor_list)

[['Jenna Floyd', 'Nephrologist', '68 Spring Street Marysville, OH 43040', 'Permanent', '_Nephrology', 38], ['Ollie Holloway', 'Nephrologist', '50 Water Street Gulfport, MS 39503', 'Visiting', '_Nephrology', 39], ['Dennis Young', 'Nephrologist', '986 Lexington Court Tacoma, WA 98444', 'Permanent', '_Nephrology', 35], ['Marlon Carpenter', 'Microbiologist', '146 Route 9 Media, PA 19063', 'Permanent', '_Microbiology', 40], ['Clayton Lynch', 'Microbiologist', '769 Sycamore Street Niles, MI 49120', 'Visiting', '_Microbiology', 36], ['Barbara Scott', 'Microbiologist', '621 Ridge Avenue Elkhart, IN 46514', 'Permanent', '_Microbiology', 52], ['Joe Powell', 'Oncologist', '230 Durham Road Allentown, PA 18102', 'Permanent', '_Oncology', 55], ['Anne Griffin', 'Oncologist', '755 Front Street South Vincentown, NJ 08088', 'Trainee', '_Oncology', 45], ['Frank Murphy', 'Oncologist', '15 College Avenue Great Falls, MT 59404', 'Permanent', '_Oncology', 39], ['Brandon Smith', 'Oncologist', '309 Aspen Drive West Roxbury, MA 02132', 'Permanent', '_Oncology', 40], ['Fred Hill', 'Cardiologist', '374 Westminster Drive Florence, SC 29501', 'Permanent', '_Cardiology', 41], ['Terry Thomas', 'Cardiologist', '418 Belmont Avenue Canyon Country, CA 91387', 'Trainee', '_Cardiology', 43], ['Louise Garcia', 'Cardiologist', '900 York Road Newark, NJ 07103', 'Visiting', '_Cardiology', 38], ['Gary Patterson', 'Cardiologist', '924 2nd Street New Castle, PA 16101', 'Permanent', '_Cardiology', 50], ['Samuel Gonzalez', 'Surgerist', '79 North Street Mishawaka, IN 46544', 'Permanent', '_General_Surgery', 47], ['Phillip Nelson', 'Surgerist', '973 Manor Drive Mcdonough, GA 30252', 'Permanent', '_General_Surgery', 45], ['Kathleen Perry', 'General Doctor', '830 Ashley Court Evansville, IN 47711', 'Permanent', '_Walk_in_Clinic', 45], ['Janice Williams', 'General Doctor', '577 13th Street Chesterfield, VA 23832', 'Permanent', '_Walk_in_Clinic', 47], ['Evelyn Cooper', 'General Doctor', '311 Route 44 Stamford, CT 06902', 'Trainee', '_Walk_in_Clinic', 60], ['Roy Johnson', 'General Doctor', '355 Cambridge Road Havertown, PA 19083', 'Permanent', '_Walk_in_Clinic', 59]]

# 3번 문제

In [81]:
# make the doctor_list to a DataFrame form
import pandas as pd
df = pd.DataFrame(hospital)
df.columns = ['Name', 'Specialty', 'Address', 'Relationship', 'WorksIn', 'Age']
df

,Name,Specialty,Address,Relationship,WorksIn,Age
0,Priscilla Arnold,Nephrologist,"326 Willow Street Rowlett, TX 75088",Trainee,_Nephrology,NaN
1,Jenna Floyd,Nephrologist,"68 Spring Street Marysville, OH 43040",Permanent,_Nephrology,38.0
2,Ollie Holloway,Nephrologist,"50 Water Street Gulfport, MS 39503",Visiting,_Nephrology,39.0
3,Dennis Young,Nephrologist,"986 Lexington Court Tacoma, WA 98444",Permanent,_Nephrology,35.0
4,Marlon Carpenter,Microbiologist,"146 Route 9 Media, PA 19063",Permanent,_Microbiology,40.0
5,Clayton Lynch,Microbiologist,"769 Sycamore Street Niles, MI 49120",Visiting,_Microbiology,36.0
6,Barbara Scott,Microbiologist,"621 Ridge Avenue Elkhart, IN 46514",Permanent,_Microbiology,52.0
7,Joe Powell,Oncologist,"230 Durham Road Allentown, PA 18102",Permanent,_Oncology,55.0
8,Anne Griffin,Oncologist,"755 Front Street South Vincentown, NJ 08088",Trainee,_Oncology,45.0
9,Frank Murphy,Oncologist,"15 College Avenue Great Falls, MT 59404",Permanent,_Oncology,39.0
10,Brandon Smith,Oncologist,"309 Aspen Drive West Roxbury, MA 02132",Permanent,_Oncology,40.0
11,Fred Hill,Cardiologist,"374 Westminster Drive Florence, SC 29501",Permanent,_Cardiology,41.0
12,Terry Thomas,Cardiologist,"418 Belmont Avenue Canyon Country, CA 91387",Trainee,_Cardiology,43.0
13,Louise Garcia,Cardiologist,"900 York Road Newark, NJ 07103",Visiting,_Cardiology,38.0
14,Gary Patterson,Cardiologist,"924 2nd Street New Castle, PA 16101",Permanent,_Cardiology,50.0
15,Samuel Gonzalez,Surgerist,"79 North Street Mishawaka, IN 46544",Permanent,_General_Surgery,47.0
16,Phillip Nelson,Surgerist,"973 Manor Drive Mcdonough, GA 30252",Permanent,_General_Surgery,45.0
17,Kathleen Perry,General Doctor,"830 Ashley Court Evansville, IN 47711",Permanent,_Walk_in_Clinic,45.0
18,Janice Williams,General Doctor,"577 13th Street Chesterfield, VA 23832",Permanent,_Walk_in_Clinic,47.0
19,Evelyn Cooper,General Doctor,"311 Route 44 Stamford, CT 06902",Trainee,_Walk_in_Clinic,60.0
20,Roy Johnson,General Doctor,"355 Cambridge Road Havertown, PA 19083",Permanent,_Walk_in_Clinic,59.0

# 4번 문제

In [82]:
df.loc[2:5, ['Name', 'Specialty', 'Relationship']]

               Name       Specialty Relationship
2    Ollie Holloway    Nephrologist     Visiting
3      Dennis Young    Nephrologist    Permanent
4  Marlon Carpenter  Microbiologist    Permanent
5     Clayton Lynch  Microbiologist     Visiting

# 5번 문제

In [83]:
df.drop('WorksIn', axis=1, inplace=True)
df.loc[3, 'Name'] = '김남민'
df

,Name,Specialty,Address,Relationship,Age
0,Priscilla Arnold,Nephrologist,"326 Willow Street Rowlett, TX 75088",Trainee,NaN
1,Jenna Floyd,Nephrologist,"68 Spring Street Marysville, OH 43040",Permanent,38.0
2,Ollie Holloway,Nephrologist,"50 Water Street Gulfport, MS 39503",Visiting,39.0
3,김남민,Nephrologist,"986 Lexington Court Tacoma, WA 98444",Permanent,35.0
4,Marlon Carpenter,Microbiologist,"146 Route 9 Media, PA 19063",Permanent,40.0
5,Clayton Lynch,Microbiologist,"769 Sycamore Street Niles, MI 49120",Visiting,36.0
6,Barbara Scott,Microbiologist,"621 Ridge Avenue Elkhart, IN 46514",Permanent,52.0
7,Joe Powell,Oncologist,"230 Durham Road Allentown, PA 18102",Permanent,55.0
8,Anne Griffin,Oncologist,"755 Front Street South Vincentown, NJ 08088",Trainee,45.0
9,Frank Murphy,Oncologist,"15 College Avenue Great Falls, MT 59404",Permanent,39.0
10,Brandon Smith,Oncologist,"309 Aspen Drive West Roxbury, MA 02132",Permanent,40.0
11,Fred Hill,Cardiologist,"374 Westminster Drive Florence, SC 29501",Permanent,41.0
12,Terry Thomas,Cardiologist,"418 Belmont Avenue Canyon Country, CA 91387",Trainee,43.0
13,Louise Garcia,Cardiologist,"900 York Road Newark, NJ 07103",Visiting,38.0
14,Gary Patterson,Cardiologist,"924 2nd Street New Castle, PA 16101",Permanent,50.0
15,Samuel Gonzalez,Surgerist,"79 North Street Mishawaka, IN 46544",Permanent,47.0
16,Phillip Nelson,Surgerist,"973 Manor Drive Mcdonough, GA 30252",Permanent,45.0
17,Kathleen Perry,General Doctor,"830 Ashley Court Evansville, IN 47711",Permanent,45.0
18,Janice Williams,General Doctor,"577 13th Street Chesterfield, VA 23832",Permanent,47.0
19,Evelyn Cooper,General Doctor,"311 Route 44 Stamford, CT 06902",Trainee,60.0
20,Roy Johnson,General Doctor,"355 Cambridge Road Havertown, PA 19083",Permanent,59.0

# 6번 문제

In [84]:
# save the df to SQLite database
import sqlite3
conn = sqlite3.connect('doctors.db')
df.to_sql('doctors', conn, if_exists='replace')

21